server:
  port: 9999
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stutest?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    #连接超时时间（毫秒）
    timeout: 30000

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    content-type: text/html
    # 禁用 thymeleaf 缓存
    cache: false

mybatis:
  #注意：一定要对应mapper映射xml文件的所在路径
  mapper-locations: classpath:mapper/*.xml
  # 注意：对应实体类的路径
  type-aliases-package: com.we.pojo
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

